# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

networks:
  byfn:

services:
  ca1:
    extends:
      file: base.yaml
      service: ca-base
    environment:
      - FABRIC_CA_SERVER_CA_NAME=ca-adminOrg
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.adminOrg.cybro-blockchain-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/1bf3ab720c1b0373decd900b0b9873634860b6665d490a53e99e43405c73da06_sk
      - FABRIC_CA_SERVER_PORT=7054
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.adminOrg.cybro-blockchain-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/1bf3ab720c1b0373decd900b0b9873634860b6665d490a53e99e43405c73da06_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/adminOrg.cybro-blockchain/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_adminOrg
    

  ca2:
    extends:
      file: base.yaml
      service: ca-base
    environment:
      - FABRIC_CA_SERVER_CA_NAME=ca-userOrg
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.userOrg.cybro-blockchain-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/41e05920faf56792b63af1cce6787fd65918ffc6454674377054b072f09dd6ab_sk
      - FABRIC_CA_SERVER_PORT=9054
    ports:
      - "9054:9054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.userOrg.cybro-blockchain-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/41e05920faf56792b63af1cce6787fd65918ffc6454674377054b072f09dd6ab_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/userOrg.cybro-blockchain/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_userOrg