# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer1.cybro-blockchain:
  orderer2.cybro-blockchain:
  orderer3.cybro-blockchain:
  orderer4.cybro-blockchain:
  orderer5.cybro-blockchain:
  peer1.adminOrg.cybro-blockchain:
  peer2.adminOrg.cybro-blockchain:
  peer1.userOrg.cybro-blockchain:
  peer2.userOrg.cybro-blockchain:

networks:
  byfn:

services:
  orderer1.cybro-blockchain:
    extends:
      file: base.yaml
      service: orderer-base
    container_name: orderer1.cybro-blockchain
    networks:
    - byfn
    volumes:
        - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ./crypto-config/ordererOrganizations/cybro-blockchain/orderers/orderer1.cybro-blockchain/msp:/var/hyperledger/orderer/msp
        - ./crypto-config/ordererOrganizations/cybro-blockchain/orderers/orderer1.cybro-blockchain/tls/:/var/hyperledger/orderer/tls
        - orderer1.cybro-blockchain:/var/hyperledger/production/orderer
    ports:
    - 7050:7050

  orderer2.cybro-blockchain:
    extends:
      file: base.yaml
      service: orderer-base
    container_name: orderer2.cybro-blockchain
    networks:
    - byfn
    volumes:
        - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ./crypto-config/ordererOrganizations/cybro-blockchain/orderers/orderer2.cybro-blockchain/msp:/var/hyperledger/orderer/msp
        - ./crypto-config/ordererOrganizations/cybro-blockchain/orderers/orderer2.cybro-blockchain/tls/:/var/hyperledger/orderer/tls
        - orderer2.cybro-blockchain:/var/hyperledger/production/orderer
    ports:
    - 8050:7050

  orderer3.cybro-blockchain:
    extends:
      file: base.yaml
      service: orderer-base
    container_name: orderer3.cybro-blockchain
    networks:
    - byfn
    volumes:
        - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ./crypto-config/ordererOrganizations/cybro-blockchain/orderers/orderer3.cybro-blockchain/msp:/var/hyperledger/orderer/msp
        - ./crypto-config/ordererOrganizations/cybro-blockchain/orderers/orderer3.cybro-blockchain/tls/:/var/hyperledger/orderer/tls
        - orderer3.cybro-blockchain:/var/hyperledger/production/orderer
    ports:
    - 9050:7050


  orderer4.cybro-blockchain:
    extends:
      file: base.yaml
      service: orderer-base
    container_name: orderer4.cybro-blockchain
    networks:
    - byfn
    volumes:
        - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ./crypto-config/ordererOrganizations/cybro-blockchain/orderers/orderer4.cybro-blockchain/msp:/var/hyperledger/orderer/msp
        - ./crypto-config/ordererOrganizations/cybro-blockchain/orderers/orderer4.cybro-blockchain/tls/:/var/hyperledger/orderer/tls
        - orderer4.cybro-blockchain:/var/hyperledger/production/orderer
    ports:
    - 10050:7050

  orderer5.cybro-blockchain:
    extends:
      file: base.yaml
      service: orderer-base
    container_name: orderer5.cybro-blockchain
    networks:
    - byfn
    volumes:
        - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ./crypto-config/ordererOrganizations/cybro-blockchain/orderers/orderer5.cybro-blockchain/msp:/var/hyperledger/orderer/msp
        - ./crypto-config/ordererOrganizations/cybro-blockchain/orderers/orderer5.cybro-blockchain/tls/:/var/hyperledger/orderer/tls
        - orderer5.cybro-blockchain:/var/hyperledger/production/orderer
    ports:
    - 11050:7050


  peer1.adminOrg.cybro-blockchain:
    container_name: peer1.adminOrg.cybro-blockchain
    extends:
      file: base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.adminOrg.cybro-blockchain
      - CORE_PEER_ADDRESS=peer1.adminOrg.cybro-blockchain:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer1.adminOrg.cybro-blockchain:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer2.adminOrg.cybro-blockchain:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.adminOrg.cybro-blockchain:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/adminOrg.cybro-blockchain/peers/peer1.adminOrg.cybro-blockchain/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/adminOrg.cybro-blockchain/peers/peer1.adminOrg.cybro-blockchain/tls:/etc/hyperledger/fabric/tls
        - peer1.adminOrg.cybro-blockchain:/var/hyperledger/production
    ports:
      - 7051:7051
    networks:
      - byfn

  peer2.adminOrg.cybro-blockchain:
    container_name: peer2.adminOrg.cybro-blockchain
    extends:
      file: base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer2.adminOrg.cybro-blockchain
      - CORE_PEER_ADDRESS=peer2.adminOrg.cybro-blockchain:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer2.adminOrg.cybro-blockchain:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.adminOrg.cybro-blockchain:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer2.adminOrg.cybro-blockchain:8051
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/adminOrg.cybro-blockchain/peers/peer2.adminOrg.cybro-blockchain/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/adminOrg.cybro-blockchain/peers/peer2.adminOrg.cybro-blockchain/tls:/etc/hyperledger/fabric/tls
        - peer2.adminOrg.cybro-blockchain:/var/hyperledger/production
    ports:
      - 8051:8051
    networks:
      - byfn

  peer1.userOrg.cybro-blockchain:
    container_name: peer1.userOrg.cybro-blockchain
    extends:
      file: base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.userOrg.cybro-blockchain
      - CORE_PEER_ADDRESS=peer1.userOrg.cybro-blockchain:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer1.userOrg.cybro-blockchain:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer2.userOrg.cybro-blockchain:10051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.userOrg.cybro-blockchain:9051
      - CORE_PEER_LOCALMSPID=Org2MSP
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/userOrg.cybro-blockchain/peers/peer1.userOrg.cybro-blockchain/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/userOrg.cybro-blockchain/peers/peer1.userOrg.cybro-blockchain/tls:/etc/hyperledger/fabric/tls
        - peer1.userOrg.cybro-blockchain:/var/hyperledger/production
    ports:
      - 9051:9051
    networks:
      - byfn

  peer2.userOrg.cybro-blockchain:
    container_name: peer2.userOrg.cybro-blockchain
    extends:
      file: base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer2.userOrg.cybro-blockchain
      - CORE_PEER_ADDRESS=peer2.userOrg.cybro-blockchain:10051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_CHAINCODEADDRESS=peer2.userOrg.cybro-blockchain:10052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.userOrg.cybro-blockchain:9051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer2.userOrg.cybro-blockchain:10051
      - CORE_PEER_LOCALMSPID=Org2MSP
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/userOrg.cybro-blockchain/peers/peer2.userOrg.cybro-blockchain/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/userOrg.cybro-blockchain/peers/peer2.userOrg.cybro-blockchain/tls:/etc/hyperledger/fabric/tls
        - peer2.userOrg.cybro-blockchain:/var/hyperledger/production
    ports:
      - 10051:10051
    networks:
      - byfn

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - SYS_CHANNEL=$SYS_CHANNEL
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- FABRIC_LOGGING_SPEC=DEBUG
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer1.adminOrg.cybro-blockchain:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/adminOrg.cybro-blockchain/peers/peer1.adminOrg.cybro-blockchain/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/adminOrg.cybro-blockchain/peers/peer1.adminOrg.cybro-blockchain/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/adminOrg.cybro-blockchain/peers/peer1.adminOrg.cybro-blockchain/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/adminOrg.cybro-blockchain/users/Admin@adminOrg.cybro-blockchain/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./myscripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/myscripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer1.cybro-blockchain
      - orderer2.cybro-blockchain
      - orderer3.cybro-blockchain
      - orderer4.cybro-blockchain
      - orderer5.cybro-blockchain
      - peer1.adminOrg.cybro-blockchain
      - peer2.adminOrg.cybro-blockchain
      - peer1.userOrg.cybro-blockchain
      - peer2.userOrg.cybro-blockchain
    networks:
      - byfn


  ca1:
    extends:
      file: base.yaml
      service: ca-base
    environment:
      - FABRIC_CA_SERVER_CA_NAME=ca-adminOrg
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.adminOrg.cybro-blockchain-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/$CA_PV1
      - FABRIC_CA_SERVER_PORT=7054
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.adminOrg.cybro-blockchain-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/$CA_PV1 -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/adminOrg.cybro-blockchain/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_adminOrg
    

  ca2:
    extends:
      file: base.yaml
      service: ca-base
    environment:
      - FABRIC_CA_SERVER_CA_NAME=ca-userOrg
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.userOrg.cybro-blockchain-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/$CA_PV2
      - FABRIC_CA_SERVER_PORT=9054
    ports:
      - "9054:9054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.userOrg.cybro-blockchain-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/$CA_PV2 -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/userOrg.cybro-blockchain/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_userOrg